language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/combined/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "tHJ+CTO/JnaU/RlTDuK97JfHG1kjAkXliOKgj5m98DZv2yIRIpQX1aKEpb/pcQzfdIitB6DYvlvF95Zlu/LFxEkjDZK/HBVyqtPQEPrtN2KlI2W0bY1jSWB3M+Jv96fU2npLcNa594iPMSoTIuQbIhwUeawZXW2yzi2WR2RgYnAdP3709tmS67p/tXaNGCD9KRF4gwQqJRrH1Oab0QskO7eJxwVBbVMEdModdsY2B503hPy06gHiLczeRnDUITsz9+0GmoCSuBHYNODtRljuLW5elrZFwEzHg7rsJZbtpd7Wmzn8mR8rhHeF/bSXevvAwHaJDPHUzUpP2FCSChyU7bH72yPLvesRlEadwPiHUI1nPDNqA2YyeYRFwUPborCg/71wLTcSyOOjlRatA+MenNQJrqeMduedlThTWp5UgUkF1Gt0y6AZgt60FKnD7Qf4SLdABFmPvZ+bwUpDbLKEStZSaUAF+t+ZFg9pn19PHMw3F+79YQE/zPxYAWUqE4NgevoY0fGataVZ/qqwlsV2tpjq2ENHpVQskVhDbeHcu2CRt634btSK2LWH8OJtyvYYTWnUzJ7FGRy8Hi3YuB1V2k1prOspJxIFkxyH2JF9FJ9HVZa7g1FK0BGf54vOUb1T70SyyYRPKo6YP4sX5PzPlRKBjQP59suTkx511BpUOsc="
